apiVersion: 1

datasources:
  - name: Loki
    uid: baddcaf6-66f9-48c5-a8aa-0fa71c25c84a
    type: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      maxLines: 1000
    isDefault: true