{
 "title": "Develop Logs",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Debug Logs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{app=\"stellarstay-app\"} | json | level=\"debug\" | line_format \"{{.msg}}\""
    }
   ]
  },
  {
   "title": "Error Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{app=\"stellarstay-app\"} | json | level=\"error\" | line_format \"{{.msg}}\""
    }
   ]
  },
  {
   "title": "Info Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{app=\"stellarstay-app\"} | json | level=\"info\" | line_format \"{{.msg}}\""
    }
   ]
  },
  {
   "title": "Info Logs Chart",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "count_over_time({app=\"stellarstay-app\"}[1m])"
    }
   ]
  }
 ]
}